<?php
//export date: 2019-11-26T17:12:12+08:00
return [
    [
        'id' => 1,
        'pid' => 0,
        'sort' => 0,
        'status' => 0,
        'node' => '',
        'title' => '系统管理',
        'icon' => 'layui-icon-set-sm',
        'url' => '#',
        'lock_version' => 3,
        'create_time' => 1546272000,
        'update_time' => 1551854113,
        'delete_time' => 0,
    ],
    [
        'id' => 2,
        'pid' => 1,
        'sort' => 0,
        'status' => 0,
        'node' => 'user.info',
        'title' => '管理人员',
        'icon' => 'layui-icon-set-sm',
        'url' => 'admin.manager/index',
        'lock_version' => 8,
        'create_time' => 1546272000,
        'update_time' => 1574317955,
        'delete_time' => 0,
    ],
    [
        'id' => 3,
        'pid' => 0,
        'sort' => 0,
        'status' => 0,
        'node' => '',
        'title' => '开发人员',
        'icon' => 'layui-icon-set-sm',
        'url' => '#',
        'lock_version' => 2,
        'create_time' => 1546272000,
        'update_time' => 1551854129,
        'delete_time' => 0,
    ],
    [
        'id' => 4,
        'pid' => 3,
        'sort' => 0,
        'status' => 0,
        'node' => 'menu.info',
        'title' => '菜单管理',
        'icon' => 'layui-icon-set-sm',
        'url' => 'admin.menu/index',
        'lock_version' => 4,
        'create_time' => 1546272000,
        'update_time' => 1574317973,
        'delete_time' => 0,
    ],
    [
        'id' => 5,
        'pid' => 3,
        'sort' => 0,
        'status' => 0,
        'node' => 'permission.info',
        'title' => '权限节点',
        'icon' => 'layui-icon-set-sm',
        'url' => 'admin.permission/index?isvue=1',
        'lock_version' => 7,
        'create_time' => 1546272000,
        'update_time' => 1574759519,
        'delete_time' => 0,
    ],
    [
        'id' => 6,
        'pid' => 1,
        'sort' => 0,
        'status' => 0,
        'node' => 'role.info',
        'title' => '角色管理',
        'icon' => 'layui-icon-set-sm',
        'url' => 'admin.role/index',
        'lock_version' => 5,
        'create_time' => 1546272000,
        'update_time' => 1574317922,
        'delete_time' => 0,
    ],
];
