<?php
//export date: 2019-04-16T13:26:08+08:00
return [
    [
        'id' => 1,
        'pid' => 0,
        'sort' => 0,
        'status' => 0,
        'node' => '',
        'title' => '系统管理',
        'icon' => 'layui-icon-set-sm',
        'url' => '#',
        'lock_version' => 3,
        'create_time' => 1546272000,
        'update_time' => 1551854113,
        'delete_time' => 0,
    ],
    [
        'id' => 2,
        'pid' => 1,
        'sort' => 0,
        'status' => 0,
        'node' => 'febbcd83',
        'title' => '管理人员',
        'icon' => 'layui-icon-set-sm',
        'url' => 'admin.manager/index',
        'lock_version' => 3,
        'create_time' => 1546272000,
        'update_time' => 1551854120,
        'delete_time' => 0,
    ],
    [
        'id' => 3,
        'pid' => 0,
        'sort' => 0,
        'status' => 0,
        'node' => '',
        'title' => '开发人员',
        'icon' => 'layui-icon-set-sm',
        'url' => '#',
        'lock_version' => 2,
        'create_time' => 1546272000,
        'update_time' => 1551854129,
        'delete_time' => 0,
    ],
    [
        'id' => 4,
        'pid' => 3,
        'sort' => 0,
        'status' => 0,
        'node' => '2b3f4081',
        'title' => '菜单管理',
        'icon' => 'layui-icon-set-sm',
        'url' => 'admin.menu/index',
        'lock_version' => 3,
        'create_time' => 1546272000,
        'update_time' => 1551868643,
        'delete_time' => 0,
    ],
    [
        'id' => 5,
        'pid' => 3,
        'sort' => 0,
        'status' => 0,
        'node' => '59ca800b',
        'title' => '权限节点',
        'icon' => 'layui-icon-set-sm',
        'url' => 'admin.permission/node',
        'lock_version' => 3,
        'create_time' => 1546272000,
        'update_time' => 1551868650,
        'delete_time' => 0,
    ],
    [
        'id' => 6,
        'pid' => 1,
        'sort' => 0,
        'status' => 0,
        'node' => '524560f2',
        'title' => '角色管理',
        'icon' => 'layui-icon-set-sm',
        'url' => 'admin.role/index',
        'lock_version' => 2,
        'create_time' => 1546272000,
        'update_time' => 1551854125,
        'delete_time' => 0,
    ],
];
