<?php
//export date: 2019-04-16T13:26:10+08:00
return [
    [
        'id' => 1,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.admin.index',
        'hash' => '95e5ce69',
        'lkey' => '1',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Index',
        'alias_name' => '主页模块',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 2,
        'pid' => 1,
        'genre' => 2,
        'nkey' => 'app.controller.admin.index-index',
        'hash' => 'a80ceae8',
        'lkey' => '1-2',
        'level' => 2,
        'action' => 'index',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Index',
        'alias_name' => '主页',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 3,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.admin.login',
        'hash' => '217dda00',
        'lkey' => '3',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Login',
        'alias_name' => '登录模块',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 4,
        'pid' => 3,
        'genre' => 2,
        'nkey' => 'app.controller.admin.login-index',
        'hash' => 'b71a129d',
        'lkey' => '3-4',
        'level' => 2,
        'action' => 'index',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Login',
        'alias_name' => '主页',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 5,
        'pid' => 3,
        'genre' => 2,
        'nkey' => 'app.controller.admin.login-check',
        'hash' => '9dd0e059',
        'lkey' => '3-5',
        'level' => 2,
        'action' => 'check',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Login',
        'alias_name' => '状态检查',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 6,
        'pid' => 3,
        'genre' => 2,
        'nkey' => 'app.controller.admin.login-captcha',
        'hash' => 'f1870e4b',
        'lkey' => '3-6',
        'level' => 2,
        'action' => 'captcha',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Login',
        'alias_name' => '验证码',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 7,
        'pid' => 3,
        'genre' => 2,
        'nkey' => 'app.controller.admin.login-login',
        'hash' => '7d6daf5c',
        'lkey' => '3-7',
        'level' => 2,
        'action' => 'login',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Login',
        'alias_name' => '登录',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 8,
        'pid' => 3,
        'genre' => 2,
        'nkey' => 'app.controller.admin.login-logout',
        'hash' => '03e76e29',
        'lkey' => '3-8',
        'level' => 2,
        'action' => 'logout',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Login',
        'alias_name' => '注销',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 9,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.admin.main',
        'hash' => '43145b62',
        'lkey' => '9',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Main',
        'alias_name' => '系统模块',
        'description' => '',
        'flags' => 1,
    ],
    [
        'id' => 10,
        'pid' => 9,
        'genre' => 2,
        'nkey' => 'app.controller.admin.main-index',
        'hash' => '9836e9e3',
        'lkey' => '9-10',
        'level' => 2,
        'action' => 'index',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Main',
        'alias_name' => '主页',
        'description' => '',
        'flags' => 1,
    ],
    [
        'id' => 11,
        'pid' => 9,
        'genre' => 2,
        'nkey' => 'app.controller.admin.main-sysinfo',
        'hash' => 'eb2ddaae',
        'lkey' => '9-11',
        'level' => 2,
        'action' => 'sysinfo',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Main',
        'alias_name' => '系统信息',
        'description' => '',
        'flags' => 1,
    ],
    [
        'id' => 12,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.admin.manager',
        'hash' => '7fa27082',
        'lkey' => '12',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Manager',
        'alias_name' => '人员模块',
        'description' => '',
        'flags' => 7,
    ],
    [
        'id' => 13,
        'pid' => 12,
        'genre' => 2,
        'nkey' => 'app.controller.admin.manager-index',
        'hash' => 'febbcd83',
        'lkey' => '12-13',
        'level' => 2,
        'action' => 'index',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Manager',
        'alias_name' => '主页',
        'description' => '',
        'flags' => 7,
    ],
    [
        'id' => 14,
        'pid' => 12,
        'genre' => 2,
        'nkey' => 'app.controller.admin.manager-table',
        'hash' => 'a90930f7',
        'lkey' => '12-14',
        'level' => 2,
        'action' => 'table',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Manager',
        'alias_name' => '数据列表',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 15,
        'pid' => 12,
        'genre' => 2,
        'nkey' => 'app.controller.admin.manager-pageedit',
        'hash' => 'ee345e12',
        'lkey' => '12-15',
        'level' => 2,
        'action' => 'pageedit',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Manager',
        'alias_name' => '编辑用户页面',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 16,
        'pid' => 12,
        'genre' => 2,
        'nkey' => 'app.controller.admin.manager-changepassword',
        'hash' => '4712ae68',
        'lkey' => '12-16',
        'level' => 2,
        'action' => 'changepassword',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Manager',
        'alias_name' => '修改密码',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 17,
        'pid' => 12,
        'genre' => 2,
        'nkey' => 'app.controller.admin.manager-save',
        'hash' => '5259d520',
        'lkey' => '12-17',
        'level' => 2,
        'action' => 'save',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Manager',
        'alias_name' => '增加/修改用户',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 18,
        'pid' => 12,
        'genre' => 2,
        'nkey' => 'app.controller.admin.manager-delete',
        'hash' => '8017ca52',
        'lkey' => '12-18',
        'level' => 2,
        'action' => 'delete',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Manager',
        'alias_name' => '删除用户',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 19,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.admin.menu',
        'hash' => 'ec482684',
        'lkey' => '19',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Menu',
        'alias_name' => '',
        'description' => '',
        'flags' => 7,
    ],
    [
        'id' => 20,
        'pid' => 19,
        'genre' => 2,
        'nkey' => 'app.controller.admin.menu-index',
        'hash' => '2b3f4081',
        'lkey' => '19-20',
        'level' => 2,
        'action' => 'index',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Menu',
        'alias_name' => '',
        'description' => '',
        'flags' => 7,
    ],
    [
        'id' => 21,
        'pid' => 19,
        'genre' => 2,
        'nkey' => 'app.controller.admin.menu-table',
        'hash' => 'd81a828d',
        'lkey' => '19-21',
        'level' => 2,
        'action' => 'table',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Menu',
        'alias_name' => '',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 22,
        'pid' => 19,
        'genre' => 2,
        'nkey' => 'app.controller.admin.menu-edit',
        'hash' => 'cf1aca17',
        'lkey' => '19-22',
        'level' => 2,
        'action' => 'edit',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Menu',
        'alias_name' => '',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 23,
        'pid' => 19,
        'genre' => 2,
        'nkey' => 'app.controller.admin.menu-save',
        'hash' => '3ea2eca6',
        'lkey' => '19-23',
        'level' => 2,
        'action' => 'save',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Menu',
        'alias_name' => '',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 24,
        'pid' => 19,
        'genre' => 2,
        'nkey' => 'app.controller.admin.menu-export',
        'hash' => 'ba354581',
        'lkey' => '19-24',
        'level' => 2,
        'action' => 'export',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Menu',
        'alias_name' => '',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 25,
        'pid' => 19,
        'genre' => 2,
        'nkey' => 'app.controller.admin.menu-delete',
        'hash' => '5829d338',
        'lkey' => '19-25',
        'level' => 2,
        'action' => 'delete',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Menu',
        'alias_name' => '',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 26,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.admin.permission',
        'hash' => '070c7494',
        'lkey' => '26',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Permission',
        'alias_name' => '权限控制模块',
        'description' => '',
        'flags' => 7,
    ],
    [
        'id' => 27,
        'pid' => 26,
        'genre' => 2,
        'nkey' => 'app.controller.admin.permission-node',
        'hash' => '59ca800b',
        'lkey' => '26-27',
        'level' => 2,
        'action' => 'node',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Permission',
        'alias_name' => '主页',
        'description' => '',
        'flags' => 7,
    ],
    [
        'id' => 28,
        'pid' => 26,
        'genre' => 2,
        'nkey' => 'app.controller.admin.permission-nodelist',
        'hash' => 'c162dc93',
        'lkey' => '26-28',
        'level' => 2,
        'action' => 'nodelist',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Permission',
        'alias_name' => '数据列表',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 29,
        'pid' => 26,
        'genre' => 2,
        'nkey' => 'app.controller.admin.permission-update',
        'hash' => '01e3919a',
        'lkey' => '26-29',
        'level' => 2,
        'action' => 'update',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Permission',
        'alias_name' => '修改别名/注释',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 30,
        'pid' => 26,
        'genre' => 2,
        'nkey' => 'app.controller.admin.permission-generatenodes',
        'hash' => '22acae39',
        'lkey' => '26-30',
        'level' => 2,
        'action' => 'generatenodes',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Permission',
        'alias_name' => '重新生成节点',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 31,
        'pid' => 26,
        'genre' => 2,
        'nkey' => 'app.controller.admin.permission-exportnodes',
        'hash' => 'ec39a01e',
        'lkey' => '26-31',
        'level' => 2,
        'action' => 'exportnodes',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Permission',
        'alias_name' => '',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 32,
        'pid' => 26,
        'genre' => 2,
        'nkey' => 'app.controller.admin.permission-saveflags',
        'hash' => '5c6e2e11',
        'lkey' => '26-32',
        'level' => 2,
        'action' => 'saveflags',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Permission',
        'alias_name' => '修改控制标识',
        'description' => '登录后启用、加入权限控制、加入菜单控制的三个标识',
        'flags' => 3,
    ],
    [
        'id' => 33,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.admin.role',
        'hash' => 'b2100bd7',
        'lkey' => '33',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '角色模块',
        'description' => '',
        'flags' => 7,
    ],
    [
        'id' => 34,
        'pid' => 33,
        'genre' => 2,
        'nkey' => 'app.controller.admin.role-index',
        'hash' => '524560f2',
        'lkey' => '33-34',
        'level' => 2,
        'action' => 'index',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '主页',
        'description' => '',
        'flags' => 7,
    ],
    [
        'id' => 35,
        'pid' => 33,
        'genre' => 2,
        'nkey' => 'app.controller.admin.role-table',
        'hash' => 'e4f63962',
        'lkey' => '33-35',
        'level' => 2,
        'action' => 'table',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '数据列表',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 36,
        'pid' => 33,
        'genre' => 2,
        'nkey' => 'app.controller.admin.role-pageedit',
        'hash' => '55883421',
        'lkey' => '33-36',
        'level' => 2,
        'action' => 'pageedit',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '编辑角色页面',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 37,
        'pid' => 33,
        'genre' => 2,
        'nkey' => 'app.controller.admin.role-save',
        'hash' => '31a1dfeb',
        'lkey' => '33-37',
        'level' => 2,
        'action' => 'save',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '增加/修改角色',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 38,
        'pid' => 33,
        'genre' => 2,
        'nkey' => 'app.controller.admin.role-permission',
        'hash' => 'e34743e1',
        'lkey' => '33-38',
        'level' => 2,
        'action' => 'permission',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '权限分配页面',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 39,
        'pid' => 33,
        'genre' => 2,
        'nkey' => 'app.controller.admin.role-savepermission',
        'hash' => 'edb1889c',
        'lkey' => '33-39',
        'level' => 2,
        'action' => 'savepermission',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '保存权限分配',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 40,
        'pid' => 33,
        'genre' => 2,
        'nkey' => 'app.controller.admin.role-menu',
        'hash' => '10508b01',
        'lkey' => '33-40',
        'level' => 2,
        'action' => 'menu',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '菜单分配页面',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 41,
        'pid' => 33,
        'genre' => 2,
        'nkey' => 'app.controller.admin.role-savemenu',
        'hash' => 'a8262d5c',
        'lkey' => '33-41',
        'level' => 2,
        'action' => 'savemenu',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '保存菜单分配',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 42,
        'pid' => 33,
        'genre' => 2,
        'nkey' => 'app.controller.admin.role-delete',
        'hash' => 'a7082ad9',
        'lkey' => '33-42',
        'level' => 2,
        'action' => 'delete',
        'sort' => 255,
        'class_name' => 'app\\controller\\admin\\Role',
        'alias_name' => '删除角色',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 43,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.index',
        'hash' => 'b1a98764',
        'lkey' => '43',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\Index',
        'alias_name' => '',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 44,
        'pid' => 43,
        'genre' => 2,
        'nkey' => 'app.controller.index-index',
        'hash' => '35bbf6e1',
        'lkey' => '43-44',
        'level' => 2,
        'action' => 'index',
        'sort' => 255,
        'class_name' => 'app\\controller\\Index',
        'alias_name' => '',
        'description' => '',
        'flags' => 0,
    ],
    [
        'id' => 45,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.upload',
        'hash' => 'd1fbbc19',
        'lkey' => '45',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\Upload',
        'alias_name' => '上传文件',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 46,
        'pid' => 45,
        'genre' => 2,
        'nkey' => 'app.controller.upload-image',
        'hash' => '2dc86459',
        'lkey' => '45-46',
        'level' => 2,
        'action' => 'image',
        'sort' => 255,
        'class_name' => 'app\\controller\\Upload',
        'alias_name' => '单图片上传',
        'description' => '',
        'flags' => 1,
    ],
    [
        'id' => 47,
        'pid' => 45,
        'genre' => 2,
        'nkey' => 'app.controller.upload-images',
        'hash' => '3c75ae1e',
        'lkey' => '45-47',
        'level' => 2,
        'action' => 'images',
        'sort' => 255,
        'class_name' => 'app\\controller\\Upload',
        'alias_name' => '多图片上传',
        'description' => '',
        'flags' => 1,
    ],
    [
        'id' => 48,
        'pid' => 0,
        'genre' => 1,
        'nkey' => 'app.controller.util',
        'hash' => 'a09ba884',
        'lkey' => '48',
        'level' => 1,
        'action' => '',
        'sort' => 255,
        'class_name' => 'app\\controller\\Util',
        'alias_name' => '工具模块',
        'description' => '',
        'flags' => 3,
    ],
    [
        'id' => 49,
        'pid' => 48,
        'genre' => 2,
        'nkey' => 'app.controller.util-obtaincsrftoken',
        'hash' => '050e0645',
        'lkey' => '48-49',
        'level' => 2,
        'action' => 'obtaincsrftoken',
        'sort' => 255,
        'class_name' => 'app\\controller\\Util',
        'alias_name' => '令牌',
        'description' => '',
        'flags' => 1,
    ],
];
